// ── Minecraft 1.21.11 map color data ─────────────────────────────────────────
// Base color table verified against minecraft.wiki/w/Map_item_format (62 base
// colors, ids 0–61). Final pixel color = floor(base * multiplier / 255).
// Shade index: 0 = dark (180), 1 = normal (220), 2 = bright (255).
// Shade on a map is decided by comparing a block's height against the block
// one to the NORTH: higher than north → bright, equal → normal, lower → dark.

export const MC_DATA_VERSION = 4671; // Java 1.21.11
export const MC_VERSION_LABEL = '1.21.11';
export const SHADE_MULTIPLIERS = [180, 220, 255];

export function shadeRGB(base, shadeIdx) {
  const m = SHADE_MULTIPLIERS[shadeIdx];
  return [(base[0] * m / 255) | 0, (base[1] * m / 255) | 0, (base[2] * m / 255) | 0];
}

// id → base RGB (multiplier 255 values). Id 0 (NONE/transparent) and id 12
// (WATER, unobtainable as a block color here) are intentionally absent.
export const BASE_COLORS = {
  1: { name: 'GRASS', rgb: [127, 178, 56] },
  2: { name: 'SAND', rgb: [247, 233, 163] },
  3: { name: 'WOOL', rgb: [199, 199, 199] },
  4: { name: 'FIRE', rgb: [255, 0, 0] },
  5: { name: 'ICE', rgb: [160, 160, 255] },
  6: { name: 'METAL', rgb: [167, 167, 167] },
  7: { name: 'PLANT', rgb: [0, 124, 0] },
  8: { name: 'SNOW', rgb: [255, 255, 255] },
  9: { name: 'CLAY', rgb: [164, 168, 184] },
  10: { name: 'DIRT', rgb: [151, 109, 77] },
  11: { name: 'STONE', rgb: [112, 112, 112] },
  13: { name: 'WOOD', rgb: [143, 119, 72] },
  14: { name: 'QUARTZ', rgb: [255, 252, 245] },
  15: { name: 'COLOR_ORANGE', rgb: [216, 127, 51] },
  16: { name: 'COLOR_MAGENTA', rgb: [178, 76, 216] },
  17: { name: 'COLOR_LIGHT_BLUE', rgb: [102, 153, 216] },
  18: { name: 'COLOR_YELLOW', rgb: [229, 229, 51] },
  19: { name: 'COLOR_LIGHT_GREEN', rgb: [127, 204, 25] },
  20: { name: 'COLOR_PINK', rgb: [242, 127, 165] },
  21: { name: 'COLOR_GRAY', rgb: [76, 76, 76] },
  22: { name: 'COLOR_LIGHT_GRAY', rgb: [153, 153, 153] },
  23: { name: 'COLOR_CYAN', rgb: [76, 127, 153] },
  24: { name: 'COLOR_PURPLE', rgb: [127, 63, 178] },
  25: { name: 'COLOR_BLUE', rgb: [51, 76, 178] },
  26: { name: 'COLOR_BROWN', rgb: [102, 76, 51] },
  27: { name: 'COLOR_GREEN', rgb: [102, 127, 51] },
  28: { name: 'COLOR_RED', rgb: [153, 51, 51] },
  29: { name: 'COLOR_BLACK', rgb: [25, 25, 25] },
  30: { name: 'GOLD', rgb: [250, 238, 77] },
  31: { name: 'DIAMOND', rgb: [92, 219, 213] },
  32: { name: 'LAPIS', rgb: [74, 128, 255] },
  33: { name: 'EMERALD', rgb: [0, 217, 58] },
  34: { name: 'PODZOL', rgb: [129, 86, 49] },
  35: { name: 'NETHER', rgb: [112, 2, 0] },
  36: { name: 'TERRACOTTA_WHITE', rgb: [209, 177, 161] },
  37: { name: 'TERRACOTTA_ORANGE', rgb: [159, 82, 36] },
  38: { name: 'TERRACOTTA_MAGENTA', rgb: [149, 87, 108] },
  39: { name: 'TERRACOTTA_LIGHT_BLUE', rgb: [112, 108, 138] },
  40: { name: 'TERRACOTTA_YELLOW', rgb: [186, 133, 36] },
  41: { name: 'TERRACOTTA_LIGHT_GREEN', rgb: [103, 117, 53] },
  42: { name: 'TERRACOTTA_PINK', rgb: [160, 77, 78] },
  43: { name: 'TERRACOTTA_GRAY', rgb: [57, 41, 35] },
  44: { name: 'TERRACOTTA_LIGHT_GRAY', rgb: [135, 107, 98] },
  45: { name: 'TERRACOTTA_CYAN', rgb: [87, 92, 92] },
  46: { name: 'TERRACOTTA_PURPLE', rgb: [122, 73, 88] },
  47: { name: 'TERRACOTTA_BLUE', rgb: [76, 62, 92] },
  48: { name: 'TERRACOTTA_BROWN', rgb: [76, 50, 35] },
  49: { name: 'TERRACOTTA_GREEN', rgb: [76, 82, 42] },
  50: { name: 'TERRACOTTA_RED', rgb: [142, 60, 46] },
  51: { name: 'TERRACOTTA_BLACK', rgb: [37, 22, 16] },
  52: { name: 'CRIMSON_NYLIUM', rgb: [189, 48, 49] },
  53: { name: 'CRIMSON_STEM', rgb: [148, 63, 97] },
  54: { name: 'CRIMSON_HYPHAE', rgb: [92, 25, 29] },
  55: { name: 'WARPED_NYLIUM', rgb: [22, 126, 134] },
  56: { name: 'WARPED_STEM', rgb: [58, 142, 140] },
  57: { name: 'WARPED_HYPHAE', rgb: [86, 44, 62] },
  58: { name: 'WARPED_WART_BLOCK', rgb: [20, 180, 133] },
  59: { name: 'DEEPSLATE', rgb: [100, 100, 100] },
  60: { name: 'RAW_IRON', rgb: [216, 175, 147] },
  61: { name: 'GLOW_LICHEN', rgb: [127, 167, 150] },
};

export const CATEGORIES = [
  { id: 'wool', label: 'Wool' },
  { id: 'concrete', label: 'Concrete' },
  { id: 'terracotta', label: 'Terracotta' },
  { id: 'glazed', label: 'Glazed Terracotta' },
  { id: 'powder', label: 'Concrete Powder', note: 'Falls without support' },
  { id: 'wood', label: 'Wood & Fungi' },
  { id: 'stone', label: 'Stone & Earth' },
  { id: 'nether', label: 'Nether & End' },
  { id: 'mineral', label: 'Ores & Minerals' },
  { id: 'nature', label: 'Nature & Plants' },
  { id: 'frozen', label: 'Ice & Snow' },
  { id: 'ocean', label: 'Ocean & Coral', note: 'Live coral needs adjacent water' },
  { id: 'misc', label: 'Miscellaneous' },
];

// When several selected blocks share a map color, the first entry in this
// array wins — so cheap, map-art-friendly blocks are listed first.
// flags: g = gravity (falls), s = needs a support block below,
//        w = dies without water, props = extra block state for the litematic.
const B = (mc, name, color, cat, extra = {}) => ({ id: mc, mc: `minecraft:${mc}`, name, color, cat, ...extra });
const LEAF = { props: { persistent: 'true' } };

export const BLOCKS = [
  // ── Wool ──
  B('white_wool', 'White Wool', 8, 'wool'),
  B('light_gray_wool', 'Light Gray Wool', 22, 'wool'),
  B('gray_wool', 'Gray Wool', 21, 'wool'),
  B('black_wool', 'Black Wool', 29, 'wool'),
  B('brown_wool', 'Brown Wool', 26, 'wool'),
  B('red_wool', 'Red Wool', 28, 'wool'),
  B('orange_wool', 'Orange Wool', 15, 'wool'),
  B('yellow_wool', 'Yellow Wool', 18, 'wool'),
  B('lime_wool', 'Lime Wool', 19, 'wool'),
  B('green_wool', 'Green Wool', 27, 'wool'),
  B('cyan_wool', 'Cyan Wool', 23, 'wool'),
  B('light_blue_wool', 'Light Blue Wool', 17, 'wool'),
  B('blue_wool', 'Blue Wool', 25, 'wool'),
  B('purple_wool', 'Purple Wool', 24, 'wool'),
  B('magenta_wool', 'Magenta Wool', 16, 'wool'),
  B('pink_wool', 'Pink Wool', 20, 'wool'),
  // ── Concrete ──
  B('white_concrete', 'White Concrete', 8, 'concrete'),
  B('light_gray_concrete', 'Light Gray Concrete', 22, 'concrete'),
  B('gray_concrete', 'Gray Concrete', 21, 'concrete'),
  B('black_concrete', 'Black Concrete', 29, 'concrete'),
  B('brown_concrete', 'Brown Concrete', 26, 'concrete'),
  B('red_concrete', 'Red Concrete', 28, 'concrete'),
  B('orange_concrete', 'Orange Concrete', 15, 'concrete'),
  B('yellow_concrete', 'Yellow Concrete', 18, 'concrete'),
  B('lime_concrete', 'Lime Concrete', 19, 'concrete'),
  B('green_concrete', 'Green Concrete', 27, 'concrete'),
  B('cyan_concrete', 'Cyan Concrete', 23, 'concrete'),
  B('light_blue_concrete', 'Light Blue Concrete', 17, 'concrete'),
  B('blue_concrete', 'Blue Concrete', 25, 'concrete'),
  B('purple_concrete', 'Purple Concrete', 24, 'concrete'),
  B('magenta_concrete', 'Magenta Concrete', 16, 'concrete'),
  B('pink_concrete', 'Pink Concrete', 20, 'concrete'),
  // ── Terracotta ──
  B('terracotta', 'Terracotta', 15, 'terracotta'),
  B('white_terracotta', 'White Terracotta', 36, 'terracotta'),
  B('orange_terracotta', 'Orange Terracotta', 37, 'terracotta'),
  B('magenta_terracotta', 'Magenta Terracotta', 38, 'terracotta'),
  B('light_blue_terracotta', 'Light Blue Terracotta', 39, 'terracotta'),
  B('yellow_terracotta', 'Yellow Terracotta', 40, 'terracotta'),
  B('lime_terracotta', 'Lime Terracotta', 41, 'terracotta'),
  B('pink_terracotta', 'Pink Terracotta', 42, 'terracotta'),
  B('gray_terracotta', 'Gray Terracotta', 43, 'terracotta'),
  B('light_gray_terracotta', 'Light Gray Terracotta', 44, 'terracotta'),
  B('cyan_terracotta', 'Cyan Terracotta', 45, 'terracotta'),
  B('purple_terracotta', 'Purple Terracotta', 46, 'terracotta'),
  B('blue_terracotta', 'Blue Terracotta', 47, 'terracotta'),
  B('brown_terracotta', 'Brown Terracotta', 48, 'terracotta'),
  B('green_terracotta', 'Green Terracotta', 49, 'terracotta'),
  B('red_terracotta', 'Red Terracotta', 50, 'terracotta'),
  B('black_terracotta', 'Black Terracotta', 51, 'terracotta'),
  // ── Glazed Terracotta ──
  B('white_glazed_terracotta', 'White Glazed Terracotta', 8, 'glazed'),
  B('light_gray_glazed_terracotta', 'Light Gray Glazed Terracotta', 22, 'glazed'),
  B('gray_glazed_terracotta', 'Gray Glazed Terracotta', 21, 'glazed'),
  B('black_glazed_terracotta', 'Black Glazed Terracotta', 29, 'glazed'),
  B('brown_glazed_terracotta', 'Brown Glazed Terracotta', 26, 'glazed'),
  B('red_glazed_terracotta', 'Red Glazed Terracotta', 28, 'glazed'),
  B('orange_glazed_terracotta', 'Orange Glazed Terracotta', 15, 'glazed'),
  B('yellow_glazed_terracotta', 'Yellow Glazed Terracotta', 18, 'glazed'),
  B('lime_glazed_terracotta', 'Lime Glazed Terracotta', 19, 'glazed'),
  B('green_glazed_terracotta', 'Green Glazed Terracotta', 27, 'glazed'),
  B('cyan_glazed_terracotta', 'Cyan Glazed Terracotta', 23, 'glazed'),
  B('light_blue_glazed_terracotta', 'Light Blue Glazed Terracotta', 17, 'glazed'),
  B('blue_glazed_terracotta', 'Blue Glazed Terracotta', 25, 'glazed'),
  B('purple_glazed_terracotta', 'Purple Glazed Terracotta', 24, 'glazed'),
  B('magenta_glazed_terracotta', 'Magenta Glazed Terracotta', 16, 'glazed'),
  B('pink_glazed_terracotta', 'Pink Glazed Terracotta', 20, 'glazed'),
  // ── Concrete Powder (gravity) ──
  B('white_concrete_powder', 'White Concrete Powder', 8, 'powder', { g: 1 }),
  B('light_gray_concrete_powder', 'Light Gray Concrete Powder', 22, 'powder', { g: 1 }),
  B('gray_concrete_powder', 'Gray Concrete Powder', 21, 'powder', { g: 1 }),
  B('black_concrete_powder', 'Black Concrete Powder', 29, 'powder', { g: 1 }),
  B('brown_concrete_powder', 'Brown Concrete Powder', 26, 'powder', { g: 1 }),
  B('red_concrete_powder', 'Red Concrete Powder', 28, 'powder', { g: 1 }),
  B('orange_concrete_powder', 'Orange Concrete Powder', 15, 'powder', { g: 1 }),
  B('yellow_concrete_powder', 'Yellow Concrete Powder', 18, 'powder', { g: 1 }),
  B('lime_concrete_powder', 'Lime Concrete Powder', 19, 'powder', { g: 1 }),
  B('green_concrete_powder', 'Green Concrete Powder', 27, 'powder', { g: 1 }),
  B('cyan_concrete_powder', 'Cyan Concrete Powder', 23, 'powder', { g: 1 }),
  B('light_blue_concrete_powder', 'Light Blue Concrete Powder', 17, 'powder', { g: 1 }),
  B('blue_concrete_powder', 'Blue Concrete Powder', 25, 'powder', { g: 1 }),
  B('purple_concrete_powder', 'Purple Concrete Powder', 24, 'powder', { g: 1 }),
  B('magenta_concrete_powder', 'Magenta Concrete Powder', 16, 'powder', { g: 1 }),
  B('pink_concrete_powder', 'Pink Concrete Powder', 20, 'powder', { g: 1 }),
  // ── Wood & Fungi ──
  B('oak_planks', 'Oak Planks', 13, 'wood'),
  B('spruce_planks', 'Spruce Planks', 34, 'wood'),
  B('birch_planks', 'Birch Planks', 2, 'wood'),
  B('jungle_planks', 'Jungle Planks', 10, 'wood'),
  B('acacia_planks', 'Acacia Planks', 15, 'wood'),
  B('dark_oak_planks', 'Dark Oak Planks', 26, 'wood'),
  B('mangrove_planks', 'Mangrove Planks', 28, 'wood'),
  B('cherry_planks', 'Cherry Planks', 36, 'wood'),
  B('pale_oak_planks', 'Pale Oak Planks', 14, 'wood'),
  B('bamboo_planks', 'Bamboo Planks', 18, 'wood'),
  B('crimson_planks', 'Crimson Planks', 53, 'wood'),
  B('warped_planks', 'Warped Planks', 56, 'wood'),
  B('crimson_hyphae', 'Crimson Hyphae', 54, 'wood'),
  B('warped_hyphae', 'Warped Hyphae', 57, 'wood'),
  B('mushroom_stem', 'Mushroom Stem', 3, 'wood'),
  B('brown_mushroom_block', 'Brown Mushroom Block', 10, 'wood'),
  B('red_mushroom_block', 'Red Mushroom Block', 28, 'wood'),
  // ── Stone & Earth ──
  B('stone', 'Stone', 11, 'stone'),
  B('cobblestone', 'Cobblestone', 11, 'stone'),
  B('stone_bricks', 'Stone Bricks', 11, 'stone'),
  B('andesite', 'Andesite', 11, 'stone'),
  B('gravel', 'Gravel', 11, 'stone', { g: 1 }),
  B('granite', 'Granite', 10, 'stone'),
  B('polished_granite', 'Polished Granite', 10, 'stone'),
  B('diorite', 'Diorite', 14, 'stone'),
  B('polished_diorite', 'Polished Diorite', 14, 'stone'),
  B('calcite', 'Calcite', 36, 'stone'),
  B('tuff', 'Tuff', 43, 'stone'),
  B('dripstone_block', 'Dripstone Block', 48, 'stone'),
  B('deepslate', 'Deepslate', 59, 'stone'),
  B('cobbled_deepslate', 'Cobbled Deepslate', 59, 'stone'),
  B('polished_deepslate', 'Polished Deepslate', 59, 'stone'),
  B('deepslate_bricks', 'Deepslate Bricks', 59, 'stone'),
  B('deepslate_tiles', 'Deepslate Tiles', 59, 'stone'),
  B('blackstone', 'Blackstone', 29, 'stone'),
  B('obsidian', 'Obsidian', 29, 'stone'),
  B('crying_obsidian', 'Crying Obsidian', 29, 'stone'),
  B('dirt', 'Dirt', 10, 'stone'),
  B('coarse_dirt', 'Coarse Dirt', 10, 'stone'),
  B('rooted_dirt', 'Rooted Dirt', 10, 'stone'),
  B('packed_mud', 'Packed Mud', 10, 'stone'),
  B('mud', 'Mud', 45, 'stone'),
  B('mud_bricks', 'Mud Bricks', 44, 'stone'),
  B('clay', 'Clay', 9, 'stone'),
  B('bricks', 'Bricks', 28, 'stone'),
  B('sand', 'Sand', 2, 'stone', { g: 1 }),
  B('sandstone', 'Sandstone', 2, 'stone'),
  B('smooth_sandstone', 'Smooth Sandstone', 2, 'stone'),
  B('red_sand', 'Red Sand', 15, 'stone', { g: 1 }),
  B('red_sandstone', 'Red Sandstone', 15, 'stone'),
  B('grass_block', 'Grass Block', 1, 'stone'),
  B('podzol', 'Podzol', 34, 'stone'),
  B('mycelium', 'Mycelium', 24, 'stone'),
  // ── Nether & End ──
  B('netherrack', 'Netherrack', 35, 'nether'),
  B('nether_bricks', 'Nether Bricks', 35, 'nether'),
  B('red_nether_bricks', 'Red Nether Bricks', 35, 'nether'),
  B('magma_block', 'Magma Block', 35, 'nether'),
  B('soul_sand', 'Soul Sand', 26, 'nether'),
  B('soul_soil', 'Soul Soil', 26, 'nether'),
  B('glowstone', 'Glowstone', 2, 'nether'),
  B('shroomlight', 'Shroomlight', 28, 'nether'),
  B('nether_wart_block', 'Nether Wart Block', 28, 'nether'),
  B('warped_wart_block', 'Warped Wart Block', 58, 'nether'),
  B('crimson_nylium', 'Crimson Nylium', 52, 'nether'),
  B('warped_nylium', 'Warped Nylium', 55, 'nether'),
  B('basalt', 'Basalt', 29, 'nether'),
  B('smooth_basalt', 'Smooth Basalt', 29, 'nether'),
  B('ochre_froglight', 'Ochre Froglight', 2, 'nether'),
  B('verdant_froglight', 'Verdant Froglight', 61, 'nether'),
  B('pearlescent_froglight', 'Pearlescent Froglight', 20, 'nether'),
  B('end_stone', 'End Stone', 2, 'nether'),
  B('end_stone_bricks', 'End Stone Bricks', 2, 'nether'),
  B('purpur_block', 'Purpur Block', 16, 'nether'),
  B('quartz_block', 'Quartz Block', 14, 'nether'),
  B('smooth_quartz', 'Smooth Quartz Block', 14, 'nether'),
  // ── Ores & Minerals ──
  B('iron_block', 'Block of Iron', 6, 'mineral'),
  B('gold_block', 'Block of Gold', 30, 'mineral'),
  B('diamond_block', 'Block of Diamond', 31, 'mineral'),
  B('emerald_block', 'Block of Emerald', 33, 'mineral'),
  B('lapis_block', 'Block of Lapis Lazuli', 32, 'mineral'),
  B('redstone_block', 'Block of Redstone', 4, 'mineral'),
  B('coal_block', 'Block of Coal', 29, 'mineral'),
  B('copper_block', 'Block of Copper', 15, 'mineral'),
  B('exposed_copper', 'Exposed Copper', 44, 'mineral'),
  B('weathered_copper', 'Weathered Copper', 56, 'mineral'),
  B('oxidized_copper', 'Oxidized Copper', 55, 'mineral'),
  B('raw_iron_block', 'Block of Raw Iron', 60, 'mineral'),
  B('raw_copper_block', 'Block of Raw Copper', 15, 'mineral'),
  B('raw_gold_block', 'Block of Raw Gold', 30, 'mineral'),
  B('amethyst_block', 'Block of Amethyst', 24, 'mineral'),
  B('netherite_block', 'Block of Netherite', 29, 'mineral'),
  // ── Nature & Plants ──
  B('oak_leaves', 'Oak Leaves', 7, 'nature', LEAF),
  B('azalea_leaves', 'Azalea Leaves', 7, 'nature', LEAF),
  B('cherry_leaves', 'Cherry Leaves', 20, 'nature', LEAF),
  B('moss_block', 'Moss Block', 27, 'nature'),
  B('dried_kelp_block', 'Dried Kelp Block', 27, 'nature'),
  B('melon', 'Melon', 19, 'nature'),
  B('pumpkin', 'Pumpkin', 15, 'nature'),
  B('hay_block', 'Hay Bale', 18, 'nature'),
  B('sponge', 'Sponge', 18, 'nature'),
  B('honeycomb_block', 'Honeycomb Block', 15, 'nature'),
  B('slime_block', 'Slime Block', 1, 'nature'),
  B('glow_lichen', 'Glow Lichen', 61, 'nature', { s: 1, props: { down: 'true' } }),
  // ── Ice & Snow ──
  B('snow_block', 'Snow Block', 8, 'frozen'),
  B('ice', 'Ice', 5, 'frozen'),
  B('packed_ice', 'Packed Ice', 5, 'frozen'),
  B('blue_ice', 'Blue Ice', 5, 'frozen'),
  // ── Ocean & Coral ──
  B('prismarine', 'Prismarine', 23, 'ocean'),
  B('prismarine_bricks', 'Prismarine Bricks', 31, 'ocean'),
  B('dark_prismarine', 'Dark Prismarine', 31, 'ocean'),
  B('sea_lantern', 'Sea Lantern', 14, 'ocean'),
  B('tube_coral_block', 'Tube Coral Block', 25, 'ocean', { w: 1 }),
  B('brain_coral_block', 'Brain Coral Block', 20, 'ocean', { w: 1 }),
  B('bubble_coral_block', 'Bubble Coral Block', 24, 'ocean', { w: 1 }),
  B('fire_coral_block', 'Fire Coral Block', 28, 'ocean', { w: 1 }),
  B('horn_coral_block', 'Horn Coral Block', 18, 'ocean', { w: 1 }),
  B('dead_tube_coral_block', 'Dead Tube Coral Block', 21, 'ocean'),
  B('dead_brain_coral_block', 'Dead Brain Coral Block', 21, 'ocean'),
  B('dead_bubble_coral_block', 'Dead Bubble Coral Block', 21, 'ocean'),
  B('dead_fire_coral_block', 'Dead Fire Coral Block', 21, 'ocean'),
  B('dead_horn_coral_block', 'Dead Horn Coral Block', 21, 'ocean'),
  // ── Miscellaneous ──
  B('tnt', 'TNT', 4, 'misc'),
  B('target', 'Target', 14, 'misc'),
  B('bone_block', 'Bone Block', 2, 'misc'),
  B('cobweb', 'Cobweb', 3, 'misc'),
  B('resin_block', 'Block of Resin', 15, 'misc'),
  B('resin_bricks', 'Resin Bricks', 15, 'misc'),
];

export const BLOCK_BY_ID = new Map(BLOCKS.map(b => [b.id, b]));

// Support / noobline block choices (hidden beneath art blocks, color-irrelevant)
export const SUPPORT_BLOCKS = [
  { id: 'cobblestone', name: 'Cobblestone' },
  { id: 'netherrack', name: 'Netherrack' },
  { id: 'dirt', name: 'Dirt' },
  { id: 'stone', name: 'Stone' },
  { id: 'oak_planks', name: 'Oak Planks' },
];

const ids = f => BLOCKS.filter(f).map(b => b.id);

export const BUILTIN_PRESETS = [
  { id: 'full', name: 'Full palette', desc: 'Every survival-obtainable block', blocks: ids(() => true) },
  { id: 'wool', name: 'Wool only', desc: '16 colors of wool', blocks: ids(b => b.cat === 'wool') },
  { id: 'concrete', name: 'Concrete only', desc: '16 colors of concrete', blocks: ids(b => b.cat === 'concrete') },
  { id: 'terracotta', name: 'Terracotta', desc: 'Plain + 16 stained', blocks: ids(b => b.cat === 'terracotta') },
  {
    id: 'natural', name: 'Natural', desc: 'Cheap undyed blocks',
    blocks: ['grass_block', 'dirt', 'coarse_dirt', 'stone', 'cobblestone', 'andesite', 'granite', 'diorite', 'calcite', 'tuff',
      'deepslate', 'blackstone', 'sand', 'sandstone', 'red_sand', 'gravel', 'clay', 'podzol', 'moss_block', 'oak_leaves',
      'oak_planks', 'spruce_planks', 'birch_planks', 'dark_oak_planks', 'snow_block', 'ice', 'netherrack', 'soul_soil',
      'terracotta', 'packed_mud', 'mud', 'dripstone_block', 'end_stone', 'obsidian'],
  },
  {
    id: 'grayscale', name: 'Grayscale', desc: 'Blacks, grays & whites',
    blocks: ['snow_block', 'white_wool', 'light_gray_wool', 'gray_wool', 'black_wool', 'white_concrete', 'light_gray_concrete',
      'gray_concrete', 'black_concrete', 'stone', 'deepslate', 'iron_block', 'mushroom_stem', 'clay', 'dead_tube_coral_block',
      'quartz_block', 'tuff', 'black_terracotta', 'gray_terracotta'],
  },
];
